### PR TITLE
Proposal for having MUMPS unit test

### PR DESCRIPTION
**Pull request by latug0**
The UniaxialTensileTest has been modified to support parallel processing.

However, the test case is so small that MUMPS does not accept to go for 2 procs, the case can be run only on 1 proc for the moment  with MUMPS. So first problem: is it possible to have a larger case  for UniaxialTensileTest ?

Second question : how to setup a correct postprocessing check in parallel ? Some thorough explanation of what is compared would be useful.

### CODE REVIEW

**Comment by thelfer** [comment]
Hi Guillaume,
We definitively have to get rid of this DO_USE_MPI trick and all those fake MPI calls in the test.
Thomas

**Comment by thelfer** [comment]
> So first problem: is it possible to have a larger case for UniaxialTensileTest ?
> 
> Second question : how to setup a correct postprocessing check in parallel ? Some thorough explanation of what is compared would be useful.

Both questions are related. The final results are uniform, whatever the number of elements used, so:

- it does not matter where we pick the results for the tests (i.e. we just take the first integration point here)
- one can use as much elements as we want.

**Comment by latug0** [comment]
> Hi Guillaume,
> Good idea. I am ok with the PR (but can't merge it). However, we definitively have to get rid of this DO_USE_MPI trick and all those fake MPI calls in the test.
> Thomas

Thanks for the answer. You cannot merge because it is a draft  PR currently.

**Comment by latug0** [comment]
> > So first problem: is it possible to have a larger case for UniaxialTensileTest ?
> > Second question : how to setup a correct postprocessing check in parallel ? Some thorough explanation of what is compared would be useful.
> 
> Both questions are related. The final results are uniform, whatever the number of elements used, so:
> 
>     * it does not matter where we pick the results for the tests (i.e. we just take the first integration point here)
> 
>     * one can use as much elements as we want.

Thanks for the answers. So I intend to check the results on each processes and verify that these are OK everywhere.

**Pull request merged**
