### PR TITLE
Postprocess to compute stress and strain at nodal values

### PR DESCRIPTION
**Pull request by latug0**
Work in progress. 
Related to issue #25

### CODE REVIEW

**Comment by latug0** [comment]
@thelfer where can I retrieve strain and stress at quadrature points please ? Which piece of code you would advise for me to look at ?

Typically, I need to fill up a function such as :
```
double StressCoefficient::Eval(ElementTransformation &T,                                                                                          
                               const IntegrationPoint &ip)                                                                                        
{  
   return < stress at quadrature point ip, for a given component s_i, s_j>
}
```

**Comment by thelfer** [comment]
Hi Guillaume,
Given a behaviour integrator, you can retrieve the material (of the Material class) and in the material you have access to:

- s0: the state at the beginning of the time step
- s1: the state at the end of the time step

In s1, you can access to the following members:

- gradients which are the values of the strain or the deformation gradient at beginning of the time step. The number of components is given by the `gradients_stride` member.
- thermodynamic_forces which are the values of the stresses at the end of the time step (6 components in small strain in 3D, 9 components in finite strain in 3D). The number of components is given by the `thermodynamic_forces_stride` member

**Comment by thelfer** [comment]
You may want to look at the implementation of `implementsComputeInnerForces` in the `StandardBehaviourIntegratorCRTPBase.ixx` for an example.

~~~~{.cxx}
  void StandardBehaviourIntegratorCRTPBase<Child>::implementComputeInnerForces(
      mfem::Vector &Fe,
      const mfem::FiniteElement &e,
      mfem::ElementTransformation &tr) {
    using Traits = BehaviourIntegratorTraits<Child>;
    auto &child = static_cast<Child &>(*this);
#ifdef MFEM_THREAD_SAFE
    mfem::DenseMatrix dshape(e.GetDof(), e.GetDim());
#else
    this->dshape.SetSize(e.GetDof(), e.GetDim());
#endif
    const auto nnodes = e.GetDof();
    const auto thsize = this->s1.thermodynamic_forces_stride;
    // element offset
    const auto eoffset = this->quadrature_space->getOffset(tr.ElementNo);
    Fe.SetSize(e.GetDof() * Traits::unknownsSize);
    Fe = 0.;
    const auto &ir = child.getIntegrationRule(e, tr);
    for (size_type i = 0; i != ir.GetNPoints(); ++i) {
      const auto &ip = ir.IntPoint(i);
      tr.SetIntPoint(&ip);
      // get the gradients of the shape functions
      e.CalcPhysDShape(tr, dshape);
      // get the weights associated to point ip
      const auto w = child.getIntegrationPointWeight(tr, ip);
      // offset of the integration point
      const auto o = eoffset + i;
      const auto r = child.getRotationMatrix(o);
      const auto s = this->s1.thermodynamic_forces.subspan(o * thsize, thsize);
      const auto &rs = child.rotateThermodynamicForces(s, r);
      for (size_type ni = 0; ni != nnodes; ++ni) {
        child.updateInnerForces(Fe, rs, dshape, w, ni);
      }
    }
  }  // end of implementComputeInnerForces
~~~~

Note that if you don't rotate the thermodynamic forces in orthotropic behaviours, you'll get the stresses in the material frame. If you do rotate them, you'll get them in the gobal frame.

Both information are relevant.

Thomas

**Comment by latug0** [comment]
A new version has been pushed in this branch. 
I have taken into account the multiple exports that you recommended me to do (one by material id).
Would you please have a look ?

There are some `TODÒ` to be replaced in order to compute real stress and strain components in `ParaviewExportResults.hxx`. If you have some advices here also, it would be great.

**Comment by latug0** [comment]
Replaced by pull request #39 with a new branch.

**Pull request closed without merging**
