### PR TITLE
[BUGFIX] Restore flags for handling Hypre versions prior to 2021

### PR DESCRIPTION
**Pull request by latug0**
To handle old versions of hypre which are still used nowadays.

### CODE REVIEW

**Comment by latug0** [comment]
@thelfer do you agree with this fix ?

**Comment by thelfer** [comment]
@rprat-pro I let you handle this as you made the patch to remove this flag.

**Comment by rprat-pro** [comment]
I disabled this default option in the CMakeFile. Perhaps we could check the version of Hypre to handle this flag.

I disabled this option because, in this section, there is only HypreILU that depends on the version of Hypre and this version is 2.19.

Even with Spack v0.16.0, the preferred version is 2.20.0. 

In addition, mfem handles changes with version 2.22 (using hypre_ParCSRMatrixSetRowStartsOwner), and these changes are all included in functions, unlike changes made for the version 2.19. 

Tell me if I missed something.

Raphaël

**Comment by latug0** [comment]
> I disabled this default option in the CMakeFile. Perhaps we could check the version of Hypre to handle this flag.
> 
> I disabled this option because, in this section, there is only HypreILU that depends on the version of Hypre and this version is 2.19.
> 
>
> Tell me if I missed something.
> 
> Raphaël

I understand but it seems to me I should be able to compile with Hypre 2.19 with:
- or an intelligible error produced by the compiler,
- or a successful compilation ...

For the moment, without this bugfix, I'm not able to compile mfem-mgis :(
Can you propose a solution.
G.

**Comment by rprat-pro** [comment]
We could add an Hypre requirement in the cmake, however this doesn't fix your issue and it's possible that for the next version of hypre we need to upgrade this requirement.

I think that instead of using an HYPRE_OLD variable, we could check the version of Hypre like mfem does it (in this case, we can handl features according to hypre) 

`set(MFEM_HYPRE_VERSION ${HYPRE_VERSION})`

and

```
#if MFEM_HYPRE_VERSION >= 21900
blabla
#else
MFEM_VERIFY(0, "no blabla");
#endif
```

**Comment by rprat-pro** [comment]
I added two files copied from mfem + modifications (with a copyright section). What should I do?

**Comment by latug0** [comment]
Solution is fine to me.

**Pull request merged**
