### PR TITLE
Add  a parallel testcase

### PR DESCRIPTION
**Pull request by latug0**
The programm PeriodicTest can now be run both in parallel or in serial. The choice between parallel or serial is performed using a preprocessor conditional. CMakeLists.txt of directory ` tests/` has been adapted.

### CODE REVIEW

**Comment by thelfer** [comment]
Great ! Ready to merge in `master` ?

**Comment by thelfer** [comment]
Note: in setBoundaryConditions, `reorder_space` is always true. What about cleaning it up ?
Also, Wouldn't it be nice to create an `PeriodicNonLinearEvolutionProblemClass` ?

**Comment by latug0** [comment]
> Great ! Ready to merge in `master` ?

Not yet. Still a problem for compiling in serial mode. I have to fix it.

**Comment by latug0** [comment]
> Note: in setBoundaryConditions, `reorder_space` is always true. What about cleaning it up ?

Yes, good idea. There is no mean to add complexity here.

> Also, Wouldn't it be nice to create an `PeriodicNonLinearEvolutionProblemClass` ?

I don't get the idea. Can you be more specific ?

**Comment by thelfer** [comment]
> I don't get the idea. Can you be more specific ?

IMHO, non linear periodic computations would be one of the main use case of `mfem-mgis`, so we could hide the boundary conditions setup in a dedicated class.

**Pull request merged**
