### PR TITLE
Manage MPI, distributed parallelism, error message

### PR DESCRIPTION
**Pull request by latug0**
In addition of a few features to handle parallelism, this branch proposes a way (PeriodicTest.cpp) to avoid exhibiting too much of C++ template. It should allow a smoother way to go towards Python API.

### CODE REVIEW

**Comment by latug0** [comment]
@thelfer I have taken account your remarks. No template anymore in PeriodicTest.cxx. Do you agree to go in this direction for user API ?

**Comment by thelfer** [comment]
@latug0 To be honest, this is not what I would do :)

My idea would be to:

1. rename `NonLinearEvolutionProblem` in `NonLinearEvolutionProblemImplementation`
2. create a new class `NonLinearEvolutionProblem` based on the `pimpl` idiom which would allocate either a `NonLinearEvolutionProblemImplementation<true>` or a `NonLinearEvolutionProblemImplementation<false>` object depending on the `FiniteElementDiscretization` object passed to it.
3. create abstract factories for sequential/parallel boundary conditions and sequential/parallel post-processings so that they could be added using a declarative syntax (not sure if this syntax would work) as follows:

~~~~{.cxx}
auto fed = FiniteElementDcretization(....);
NonLinearEvolutionProblem p (fed);
p.addBoundaryCondition("Dirichlet", {{"boundary": 1}, {"evolution": [](const real t){return 1.e-2 *t ;}});
~~~~

In this case, the only difference between a parallel and a sequential computation is in the declaration of the `FiniteElementDcretization` object.

Such design would be:
- Very clean for the end-user and `python` bindings.
- Very clean separation of concerns in `mfem-mgis` as the sequential and parallel part are cleary separated.

Of course, we shall discuss this to be sure which solution is better. I'll send you an invitation.

Also I like the idea of the `Manager` class, but I would call it `ConfigurationManager` and make it a singleton....

Best,

Thomas

**Comment by latug0** [comment]
Yes we need to talk. I have defined a `static constexpr` within the Manager that can be used as you suggest for FiniteElementDiscretization object to parametize the parallel/seial version. This Manager (and paralle/serial setting) can be transmitted all along the instaciations.
Then, I agree with you on some of the points you mentioned, but I would like another implementation strategy based on the Manager as a conveyer.
For the preceeding reason, I do not want to have a singleton for the Manager : it would loose the main advantage of conveying the constexpr member that is useful at compile time.

**Comment by thelfer** [comment]
Hi Guillaume,
would you have a look a the `work_pr_21` branch ?
I almost get rid of the `DO_USE_MPI` flag in the `PeriodicTest`. I now must pass a `--parallel` option to select parallel computations at runtime.
The most interesting part concerning this PR is in the `Config.hxx` and `Config.cxx` files. In particular, the `initialize` function initialize `MPI` and the `finalize` function is optional. I also used the lastest developments in `MGIS` to set a dedicated exception handler in parallel.

**Comment by latug0** [comment]
> Hi Guillaume,
> would you have a look a the `work_pr_21` branch ?
> I almost get rid of the `DO_USE_MPI` flag in the `PeriodicTest`. I now must pass a `--parallel` option to select parallel computations at runtime.
> The most interesting part concerning this PR is in the `Config.hxx` and `Config.cxx` files. In particular, the `initialize` function initialize `MPI` and the `finalize` function is optional. I also used the lastest developments in `MGIS` to set a dedicated exception handler in parallel.

I tested with the new `MGIS` version and merged with master with some improvements (commit 3e67e72).
I do agree on the singleton for managing MPI via initialize/finalize functions.
However, the ` --parallel` option seems a strange idea to me. If the user compile with MPI support, even on one process, it is a parallel version of mfem-mgis. We need to discuss what do you intend exactly to do with this option. 

I need to have a deeper look into Config.cxx and Config.hxx the next days, to see how we can remove DO_USE_MPI in some way.

**Comment by thelfer** [comment]
> I tested with the new `MGIS` version and merged with master with some improvements (commit [3e67e72](https://github.com/thelfer/mfem-mgis/commit/3e67e722063ce0ef0c0cacf6af1749653f165fec)).

Great ! However, I changed a few things:

- in `UnilateralTensileTest`, the MPI_ReduceAll is only called if MFEM_USE_MPI is defined.
- The tests are done on all processes, not only the one with rank 0
- The exit_on_failure is not required and a much standard std::exit(EXIT_FAILURE) is preferable (thanks to the singleton, the MPIFinalize function is called automatically)

> I do agree on the singleton for managing MPI via initialize/finalize functions.
> However, the ` --parallel` option seems a strange idea to me. If the user compile with MPI support, even on one process, it is a parallel version of mfem-mgis. We need to discuss what do you intend exactly to do with this option.

This option allows to test all the sequential classes even if MFEM_USE_MPI is defined. Definitively useful ! 
 
> I need to have a deeper look into Config.cxx and Config.hxx the next days, to see how we can remove DO_USE_MPI in some way.

I do thing that the `--parallel` option is the right way to go. However, we should probably change the default value of the `Parallel` parameter to `true` if `MFEM_USE_MPI` is defined...

**Pull request closed without merging**
