### PR TITLE
Add MUMPS support

### PR DESCRIPTION
**Pull request by latug0**
In order to have access to a first parallel direct solver, MUMPS support has been added.
If MFEM is compled with MFEM_USE_MUMPS option, mfem-mgis can use this solver automatically.

### CODE REVIEW

**Comment by thelfer** [comment]
Very nice ! One question though. Jacobian will be in many cases symmetric, is there any way to also support symmetric matrices in this PR ?

**Comment by latug0** [comment]
> Very nice ! One question though. Jacobian will be in many cases symmetric, is there any way to also support symmetric matrices in this PR ?

The answer is yes. I do it straightaway.

**Comment by thelfer** [comment]
BTW, the matrix in the PeriodicTest is symmetric :)

**Comment by latug0** [comment]
You are right. But I started with a quite more one-size-fits-all solution.

**Comment by latug0** [comment]
Commit 37f07b4 and
6653b39  add the support for symmetric matrices.

**Comment by thelfer** [comment]
The MUMPS solver was not correctly declared: it was in the `else`  branch of the test  `if constexpr (!parallel)`.
I changed a little bit the options. Let me know if your ok with this and if it compiles (I don't have unable `MUMPS` support so far).

**Comment by latug0** [comment]
Fine with me with the fix 9caedb9

**Pull request merged**
