### PR TITLE
Enabling configuration with built-in mfem instead of installed mfem :

### PR DESCRIPTION
**Pull request by gauthier12**
I'm am trying to compile mfem and mfem-mgis as two cmake subprojects of the same project.
To do so, I had to modify some CMake scripts.
This pull request is a first version in order to begin the discussion, I'm not completely sure of what I've done but it seems to work.
Here is what I've done : 
 - Detect if the mfem is defined, if so, no call to find-package(mfem)
 - Detect if the check target is defined, if so, rename check target to mgis_check to prevent conflict with mfem check target.
 - Putting MFEM include directory in PRIVATE and add MFEM include for the examples

As it was, I had Cmake errors telling me that an include directory was in the source directory.
The correction I found was to move mfem include directory from PUBLIC to PRIVATE and add the mfem directory to the examples.

### CODE REVIEW

**Comment by thelfer** [comment]
Hi Gauthier,

I'll check your PR tonight (on vacation this week). I

However, this remark:

> As it was, I had Cmake errors telling me that an include directory was in the source directory.

remind me of the following lines in `MGIS`, i.e. one can use different location at build time and at installation time.

~~~~
target_include_directories(MFrontGenericInterface
   PUBLIC 
   $<BUILD_INTERFACE:${CMAKE_SOURCE_DIR}/include>
   $<INSTALL_INTERFACE:include>)
~~~~

Would you check if this could be a better way to solve your issue ?

Best,

Thomas

**Comment by gauthier12** [comment]
You were right, the  $<BUILD_INTERFACE:> condition did the trick.
I reverted the test CMakelist to the original version

**Comment by thelfer** [comment]
The changes are nice. However,  in this declaration:

~~~~
 target_include_directories(${name}
￼    SYSTEM PUBLIC "$<BUILD_INTERFACE:${MFEM_INCLUDE_DIRS}>")
~~~~

I feel that the `INSTALL_INTERFACE` case is missing, don't you think ?

**Comment by gauthier12** [comment]
Yes and no.
I think you need the INSTALL_INTERFACE to point to the installed built-in mfem include directory which is compiled at the same time as mfem-mgis, so with the cmake installation prefix. 
So I would need to add
```
 target_include_directories(${name} 
 SYSTEM PUBLIC "$<BUILD_INTERFACE:${MFEM_INCLUDE_DIRS}>"
PUBLIC $<INSTALL_INTERFACE:include>
)
```
but this folder is already added line 13

**Comment by gauthier12** [comment]
Do you think we can merge ?

**Comment by thelfer** [comment]
Let's merge. If the generated `cmake` files are rotten, I'll open a ticket and assign it to you :)

**Pull request merged**
