### PR TITLE
Add selection of master process for outputing

### PR DESCRIPTION
**Pull request by latug0**
Proposal for doing prints on standard outputs only on master process.

### CODE REVIEW

**Comment by latug0** [comment]
@thelfer If you wish,  we can extend this proposal to other examples of the `testsdirectory.

**Review by thelfer — APPROVED** [review]

**Comment by thelfer** [comment]
Hi Guillaume,
I would also add a getLogStream() method which would by default return mfem::out.
In debug mode (not yet implemented) we could redirect the output stream to a file (per MPI-process), etc....
Thomas

**Comment by latug0** [comment]
What do you think of this version ? Should I use this API within all programs ?

**Comment by thelfer** [comment]
For the sake of homogeneity with the reste of the API, wouldn't be `getOutputStream` and `getErrorStream` more appropriate names ?

**Comment by thelfer** [comment]
Apart from the names of the functions, it's fine for me to propagate this API everywhere in the code.

**Comment by latug0** [comment]
OK done.

**Comment by thelfer** [comment]
It's fine for me. Ready to merge !

**Pull request merged**
