### PR TITLE
Fix compilation issue serial

### PR DESCRIPTION
**Pull request by latug0**
This fix allows to compile in serial mode and parallel mode.
Can you check that in serial mode everything is OK for you ?

### CODE REVIEW

**Comment by thelfer** [comment]
Ok, we will make something "cleaner" later.

**Comment by thelfer** [comment]
Tests are ok in serial. Ok for the merge in master ?

**Comment by latug0** [comment]
> Tests are ok in serial. Ok for the merge in master ?

Fine.

**Comment by thelfer** [comment]
Done

**Pull request merged**
