### PR TITLE
Shorten cmake compilation time 

### PR DESCRIPTION
**Pull request by latug0**
Put some variables in cache in order to speedup compilation process.
Correct a few things compared to PR #30 .

### CODE REVIEW

**Comment by thelfer** [comment]
Maybe I did not understand the purpose of the patch but I would expect that the call to `make` would not trigger flags tests again:

```bash
$ rm -fr * && cmake ~/codes/mfem-mgis/master/src/mfem-mgis -DMFEM_DIR=/home/th202608/codes/mfem/master/install/lib/cmake/mfem/ -DMFrontGenericInterface_DIR=/home/th202608/codes/mgis/master/install-python-3.7/share/mgis/cmake/
...
$ touch ~/codes/mfem-mgis/master/src/mfem-mgis/CMakeLists.txt 
th202608@pleiades093:/tmp/build-mfem-mgis$ make
-- enabling flag 'Wno-conversion'
-- enabling flag 'Wall'
-- enabling flag 'W'
-- enabling flag 'Wshadow'
```

**Comment by latug0** [comment]
The "-- enabling" mesage is still printed. But behind the check is not done because cached variables keep the result of the check.
The only thing that should change is the duration of the compilation because flags check are not done.

Can you check this please  ?
```
grep -e suggest -e covered CMakeCache.txt
```
The previous version gives :
```
//Test Wno-covered-switch-default_AVAILABLE
Wno-covered-switch-default_AVAILABLE:INTERNAL=
//Test Wsuggest-override_AVAILABLE
Wsuggest-override_AVAILABLE:INTERNAL=1
```

The new version:
```
//Test Wno-covered-switch-default_AVAILABLE
Wno-covered-switch-default_AVAILABLE:BOOL=FALSE
//Test Wsuggest-override_AVAILABLE
Wsuggest-override_AVAILABLE:BOOL=TRUE

```

**Comment by thelfer** [comment]
Even if I change the `tfel_enable_cxx_compiler_flag2 ` function for:

```cmake
MACRO(tfel_enable_cxx_compiler_flag2 out flag var)
  if (NOT DEFINED CACHE{${var}})
    if(MSVC)
      TFEL_CHECK_CXX_COMPILER_FLAG("/${flag}" ${var})
    else(MSVC)
      TFEL_CHECK_CXX_COMPILER_FLAG("-${flag}" ${var})
    endif(MSVC)
    IF(${var})
      MESSAGE(STATUS "enabling flag '${flag}'")
    ELSE(${${var})
      MESSAGE(STATUS "flag '${flag}' disabled")
    ENDIF(${var})
  endif(NOT DEFINED CACHE{${var}})
  IF(${var})
    if(MSVC)
      SET(${out} "/${flag} ${${out}}")
    else(MSVC)
      SET(${out} "-${flag} ${${out}}")
    endif(MSVC)
  ENDIF(${var})
ENDMACRO(tfel_enable_cxx_compiler_flag2)
```

I still get the message, which means that the compiler still get called, doesn't it ?

**Comment by latug0** [comment]
Can you give me the result of the grep command please ?
` grep -e suggest -e covered CMakeCache.txt`

**Comment by thelfer** [comment]
```bash
$ grep -e suggest -e covered CMakeCache.txt
//Test Wno-covered-switch-default_AVAILABLE
Wno-covered-switch-default_AVAILABLE:BOOL=FALSE
//Test Wsuggest-override_AVAILABLE
Wsuggest-override_AVAILABLE:BOOL=TRUE
```

**Comment by latug0** [comment]
Then you should not enter in the branch ` if (NOT DEFINED CACHE{${var}}) ` of your version. You should not get the "enabling flag " print in your version of the routine ...

The command "DEFINED CACHE" is available since version 3.14 of cmake. Which version do you use ?

**Comment by latug0** [comment]
I add the requirement of CMake version 3.14 in the main `CMakeLists.txt`. Sorry for the inconvenience.

**Comment by thelfer** [comment]
I use `cmake 3.13.4` which is the default on `buster` :)
I do like this patch. I will make use of it in `TFEL`, but can't impose such requirement right now.
How about testing the `cmake` version in the `tfel_enable_cxx_compiler_flag2` version ?
For old versions, no cache. For new versions, a little speed-up. Seems fair, doesn't it ?

**Comment by latug0** [comment]
I pushed a new version that does require last versions of cmake.
The piece of code you mention has been aded.
There is still a minor problem with flags that embed the "=" sign. These flags are always checked because the storing of these name is problematic in the CMakeCache.txt. I think we can postpone this problem.

**Pull request merged**
